version: '3'

services:
  webapi:
    image: eddynguyen/motofacts
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - db
    networks:
      - moto-network
    environment:   
      ConnectionStrings__DefaultConnection: "Host=db;Port=5432;Database=MotoFactsDB;Username=postgres;Password=admin"
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: postgres
      POSTGRES_DB: MotoFactsDB
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - moto-network
networks:
  moto-network:
   driver: bridge
volumes:
  pgdata:
   
   
   
   
    