apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: backend
  namespace: nameargocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: sd2376-argocd-projects

  source:
    repoURL: https://github.com/dungnh7/sd2376_msa
    targetRevision: HEAD
    path: /src/deployment
   
  # Destination cluster and namespace to deploy the application
  destination:
    server: https://kubernetes.default.svc
    namespace: app-nameargocd

  # Sync policy
  syncPolicy:
    syncOptions:
      - CreateNamespace=true  
    automated: # automated sync by default retries failed attempts 5 times with following delays between attempts ( 5s, 10s, 20s, 40s, 80s ); retry controlled using `retry` field.
      prune: true # Specifies if resources should be pruned during auto-syncing ( false by default ).
      selfHeal: true # Specifies if partial app sync should be executed when resources are changed only in target Kubernetes cluster and no git change detected ( false by default ).
